export default [
    {
        label: "Activity",
        name: "activity"
    },
    {
        label: "City",
        name: "city"
    },
    {
        label: "State",
        name: "state",
        type: "select",
        options: [{value: "Alabama", show: "Alabama"},
            {value: "Alaska", show: "Alaska"},
            {value: "Arizona", show: "Arizona"},
            {value: "Arkansas", show: "Arkansas"},
            {value: "California", show: "California"},
            {value: "Colorado", show: "Colorado"},
            {value: "Connecticut", show: "Connecticut"},
            {value: "Delaware", show: "Delaware"},
            {value: "Florida", show: "Florida"},
            {value: "Georgia", show: "Georgia"},
            {value: "Hawaii", show: "Hawaii"},
            {value: "Idaho", show: "Idaho"},
            {value: "Illinois", show: "Illinois"},
            {value: "Indiana", show: "Indiana"},
            {value: "Iowa", show: "Iowa"},
            {value: "Kansas", show: "Kansas"},
            {value: "Kentucky", show: "Kentucky"},
            {value: "Louisiana", show: "Louisiana"},
            {value: "Maine", show: "Maine"},
            {value: "Maryland", show: "Maryland"},
            {value: "Massachusetts", show: "Massachusetts"},
            {value: "Michigan", show: "Michigan"},
            {value: "Minnesota", show: "Minnesota"},
            {value: "Mississippi", show: "Mississippi"},
            {value: "Missouri", show: "Missouri"},
            {value: "Montana", show: "Montana"},
            {value: "Nebraska", show: "Nebraska"},
            {value: "Nevada", show: "Nevada"},
            {value: "New Hampshire", show: "New Hampshire"},
            {value: "New Jersey", show: "New Jersey"},
            {value: "New Mexico", show: "New Mexico"},
            {value: "New York", show: "New York"},
            {value: "North Carolina", show: "North Carolina"},
            {value: "North Dakota", show: "North Dakota"},
            {value: "Ohio", show: "Ohio"},
            {value: "Oklahoma", show: "Oklahoma"},
            {value: "Oregon", show: "Oregon"},
            {value: "Pennsylvania", show: "Pennsylvania"},
            {value: "Rhode Island", show: "Rhode Island"},
            {value: "South Carolina", show: "South Carolina"},
            {value: "South Dakota", show: "South Dakota"},
            {value: "Tennessee", show: "Tennessee"},
            {value: "Texas", show: "Texas"},
            {value: "Utah", show: "Utah"},
            {value: "Vermont", show: "Vermont"},
            {value: "Virginia", show: "Virginia"},
            {value: "Washington", show: "Washington"},
            {value: "West Virginia", show: "West Virginia"},
            {value: "Wisconsin", show: "Wisconsin"},
            {value: "Wyoming", show: "Wyoming"}]
    }
];