export default [
    {
        label: "City",
        name: "city"
    },
    {
        label: "State",
        name: "state",
        type: "select",
        options: [{value: "AL", show: "Alabama"},
            {value: "AK", show: "Alaska"},
            {value: "AZ", show: "Arizona"},
            {value: "AR", show: "Arkansas"},
            {value: "CA", show: "California"},
            {value: "CO", show: "Colorado"},
            {value: "CT", show: "Connecticut"},
            {value: "DE", show: "Delaware"},
            {value: "FL", show: "Florida"},
            {value: "GA", show: "Georgia"},
            {value: "HI", show: "Hawaii"},
            {value: "ID", show: "Idaho"},
            {value: "IL", show: "Illinois"},
            {value: "IN", show: "Indiana"},
            {value: "IA", show: "Iowa"},
            {value: "KS", show: "Kansas"},
            {value: "KY", show: "Kentucky"},
            {value: "LA", show: "Louisiana"},
            {value: "ME", show: "Maine"},
            {value: "MD", show: "Maryland"},
            {value: "MA", show: "Massachusetts"},
            {value: "MI", show: "Michigan"},
            {value: "MN", show: "Minnesota"},
            {value: "MS", show: "Mississippi"},
            {value: "MO", show: "Missouri"},
            {value: "MT", show: "Montana"},
            {value: "NE", show: "Nebraska"},
            {value: "NV", show: "Nevada"},
            {value: "NH", show: "New Hampshire"},
            {value: "NJ", show: "New Jersey"},
            {value: "NM", show: "New Mexico"},
            {value: "NY", show: "New York"},
            {value: "NC", show: "North Carolina"},
            {value: "ND", show: "North Dakota"},
            {value: "OH", show: "Ohio"},
            {value: "OK", show: "Oklahoma"},
            {value: "OR", show: "Oregon"},
            {value: "PA", show: "Pennsylvania"},
            {value: "RI", show: "Rhode Island"},
            {value: "SC", show: "South Carolina"},
            {value: "SD", show: "South Dakota"},
            {value: "TN", show: "Tennessee"},
            {value: "TX", show: "Texas"},
            {value: "UT", show: "Utah"},
            {value: "VT", show: "Vermont"},
            {value: "VA", show: "Virginia"},
            {value: "WA", show: "Washington"},
            {value: "WV", show: "West Virginia"},
            {value: "WI", show: "Wisconsin"},
            {value: "WY", show: "Wyoming"}]
    }
];